### ISSUE TITLE
[EXPIRED] Windows standalone binary

### ISSUE THREAD

**Issue by sergeevabc** [mayankchd/movie#1]
Dear Mayank,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows w/o Node?
I’m told that either [Nexe][1] or [EnclosureJS][2] might help you to achieve that.

[1]: https://www.npmjs.com/package/nexe
[2]: http://enclosejs.com/

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by sergeevabc** [comment]
Six months passed. Err… Mayank, hello?

**Comment by brhx** [comment]
Standalone binaries can be tricky w/ node, and are generally not recommended. Any particular reason you need a `.exe` for this instead of just being able to install node?

And also looking over the documentation for `nexe`, it shouldn't be too hard to create to implement that functionality yourself in a PR if the feature is important to you.
